name: 'Obsidian Tag Organizer'
description: 'Automatically organize Obsidian tags using OpenAI API'

inputs:
  openai-api-key:
    description: 'OpenAI API Key'
    required: true
  target-folder:
    description: 'Target folder to organize tags (default: ".")'
    required: false
    default: '.'
  exclude-folders:
    description: 'List of folders to exclude (YAML list format)'
    required: false
    default: ''
  forbidden-tags:
    description: 'List of tags that should not be used (YAML list format)'
    required: false
    default: ''
  model:
    description: 'OpenAI model to use (default: "gpt-3.5-turbo")'
    required: false
    default: 'gpt-3.5-turbo'
  temperature:
    description: 'Temperature for OpenAI API (default: 0.7)'
    required: false
    default: '0.7'
  skip-invalid-frontmatter:
    description: 'Skip files with invalid front matter instead of failing (default: "true")'
    required: false
    default: 'true'
  max-tags:
    description: 'Maximum number of tags to add (default: 5)'
    required: false
    default: '5'
  max-files:
    description: 'Maximum number of files to process (default: 5)'
    required: false
    default: '5'
  max-content-length:
    description: 'Maximum content length to analyze (default: 4000)'
    required: false
    default: '4000'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'tag'
  color: 'blue' 